version: "3.8"
#host: host.docker.internal
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      SERVICES: s3
      DOCKER_HOST: unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  rabbitmq3:
    container_name: "rabbitmq"
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
    ports:
      - '5672:5672'
      - '15672:15672'
  song-db:
    container_name: song_pg
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nimda
      POSTGRES_DB: song_db
    volumes:
      - ./setup/db/song/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "5433:5432"
  tracking-db:
    container_name: tracking_pg
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nimda
      POSTGRES_DB: tracking_db
    volumes:
      - ./setup/db/tracking/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "5434:5432"