
spring:
  #  profiles: dev
  datasource:
    hikari:
      connectionTimeout: ${HIKARI_CONNECTION_TIMEOUT:20000}
      maximumPoolSize: ${HIKARI_POOL_SIZE:5}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SONG_SERVICE_DB_USERNAME:postgres}
    password: ${SONG_SERVICE_DB_PASSWORD:nimda}